/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Select the Product you wish to target
 */
#define CONFIG_REAL_VENDOR_ASUS 1
#undef  CONFIG_DEFAULTS_ASUS_EAN66
#define CONFIG_DEFAULTS_ASUS_RPN12 1
#undef  CONFIG_DEFAULTS_ASUS_RPN14
#undef  CONFIG_DEFAULTS_ASUS_RPN53
#undef  CONFIG_DEFAULTS_ASUS_RPAC52
#undef  CONFIG_DEFAULTS_ASUS_RPAC56
#undef  CONFIG_DEFAULTS_ASUS_WMPN12
#undef  CONFIG_DEFSETTING_4M32M
#define CONFIG_DEFSETTING_4M16M 1
#define CONFIG_DEFAULTS_RALINK_MT7628 1

/*
 * Kernel/Library/Defaults Selection
 */
#define CONFIG_DEFAULTS_KERNEL_2_6_36 1
#define CONFIG_CROSS_COMPILER_PATH "/opt/buildroot-gcc342/bin"

/*
 *  
 */
#undef  CONFIG_DEFAULTS_OVERRIDE
#undef  CONFIG_DEFAULTS_KERNEL
#undef  CONFIG_DEFAULTS_VENDOR
#undef  CONFIG_DEFAULTS_BUSYBOX
#undef  CONFIG_DEFAULTS_UCLIBC
#undef  CONFIG_DEFAULTS_UCLIBC_PLUS_PLUS
#undef  CONFIG_DEFAULTS_VENDOR_UPDATE
