#! /bin/sh
#############################################################################
#
# Generate the vendor/product menu entries for the top level config
#
# davidm@snapgear.com
#
#############################################################################

fix_name()
{
	echo $1 | tr '[\-\.\/\+a-z]' '[____A-Z]'
}

#############################################################################
#
# the header of the config
#

echo "mainmenu_name 'Ralink Embedded Linux Configuration'"

#############################################################################
#
# Figure out the vendor/products dynamically, allows people to add there
# own without messin with the config.in file
#

echo "mainmenu_option next_comment"
echo "comment 'Select the Product you wish to target'"

echo "choice 'Vendor' \"ASUS CONFIG_REAL_VENDOR_ASUS"
echo "                \""

echo "if [ \"\$CONFIG_REAL_VENDOR_ASUS\" = \"y\" ]; then"
echo "choice 'ASUS Products' \"EA-N66 CONFIG_DEFAULTS_ASUS_EAN66"
echo "                         RP-N12 CONFIG_DEFAULTS_ASUS_RPN12"
echo "                         RP-N14 CONFIG_DEFAULTS_ASUS_RPN14"
echo "                         RP-N53 CONFIG_DEFAULTS_ASUS_RPN53"
echo "                         RP-AC52 CONFIG_DEFAULTS_ASUS_RPAC52"
echo "                         RP-AC56 CONFIG_DEFAULTS_ASUS_RPAC56"
echo "                         WMP-N12 CONFIG_DEFAULTS_ASUS_WMPN12"
echo "                	     \""
echo "if [ \"\$CONFIG_DEFAULTS_ASUS_EAN66\" = \"y\" ]; then"
echo "choice   'Flash/SDRAM Size' \"4M/32M   CONFIG_DEFSETTING_4M32M"
echo "                            \" 4M/32M"
echo "define_bool CONFIG_DEFAULTS_RALINK_RT3883 y"
echo "elif [ \"\$CONFIG_DEFAULTS_ASUS_RPN12\" = \"y\" ]; then"
echo "choice   'Flash/SDRAM Size' \"4M/32M   CONFIG_DEFSETTING_4M32M"
echo "                              4M/16M   CONFIG_DEFSETTING_4M16M"
echo "                            \" 4M/16M"
echo "define_bool CONFIG_DEFAULTS_RALINK_MT7628 y"
echo "elif [ \"\$CONFIG_DEFAULTS_ASUS_RPN14\" = \"y\" ] || [ \"\$CONFIG_DEFAULTS_ASUS_RPN53\" = \"y\" ] || [ \"\$CONFIG_DEFAULTS_ASUS_RPAC52\" = \"y\" ] || [ \"\$CONFIG_DEFAULTS_ASUS_WMPN12\" = \"y\" ]; then"
echo "choice   'Flash/SDRAM Size' \"8M/64M   CONFIG_DEFSETTING_8M64M"
echo "                            \" 8M/64M"
echo "define_bool CONFIG_DEFAULTS_RALINK_MT7620 y"
echo "elif [ \"\$CONFIG_DEFAULTS_ASUS_RPAC56\" = \"y\" ]; then"
echo "choice   'Flash/SDRAM Size' \"8M/64M   CONFIG_DEFSETTING_8M64M"
echo "                            \" 8M/64M"
echo "define_bool CONFIG_DEFAULTS_RALINK_MT7621 y"
echo "fi"
echo "fi"
echo "endmenu"

#############################################################################

echo "mainmenu_option next_comment"
echo "comment 'Kernel/Library/Defaults Selection'"

echo "define_bool CONFIG_DEFAULTS_KERNEL_2_6_36 y"

#############################################################################
#
# the rest of the config
#

# echo "mainmenu_option next_comment"
# echo "comment 'Configuration Overrides'"

cat <<!EOF
string 'Cross Compiler Path' 			CONFIG_CROSS_COMPILER_PATH /opt/buildroot-gcc342/bin
comment ' '
bool 'Default all settings (lose changes)'	CONFIG_DEFAULTS_OVERRIDE
bool 'Customize Kernel Settings'		CONFIG_DEFAULTS_KERNEL
!EOF
[ -d modules ] &&
	echo "bool 'Customize Module Settings'	CONFIG_DEFAULTS_MODULES"
cat <<!EOF
bool 'Customize Vendor/User Settings'		CONFIG_DEFAULTS_VENDOR
bool 'Customize Busybox Settings'               CONFIG_DEFAULTS_BUSYBOX
bool 'Customize uClibc Settings'                CONFIG_DEFAULTS_UCLIBC
bool 'Customize uClibc++ Settings'              CONFIG_DEFAULTS_UCLIBC_PLUS_PLUS
bool 'Update Default Vendor Settings'		CONFIG_DEFAULTS_VENDOR_UPDATE
endmenu
!EOF

############################################################################
