/* Generated by gupnp-binding-tool */

#include <libgupnp/gupnp.h>

#ifndef GUPNP_GENERATED_CLIENT_BINDING_CONNECTIONMANAGER
#define GUPNP_GENERATED_CLIENT_BINDING_CONNECTIONMANAGER

G_BEGIN_DECLS

#ifndef __GUPNPASYNCDATA_TYPE__
#define __GUPNPASYNCDATA_TYPE__
typedef struct {GCallback cb; gpointer userdata; } GUPnPAsyncData;
#endif
static void
_free_cb_data (gpointer data, GClosure *closure)
{
  GUPnPAsyncData *cbdata = (GUPnPAsyncData *) data;
  g_slice_free1 (sizeof (*cbdata), cbdata);
}


/* action GetProtocolInfo */

static inline void
connectionmanager_get_protocol_info_action_set (GUPnPServiceAction *action,
                                                const gchar *out_source,
                                                const gchar *out_sink)
{
  gupnp_service_action_set (action,
                            "Source", G_TYPE_STRING, out_source,
                            "Sink", G_TYPE_STRING, out_sink,
                            NULL);
}

static inline gulong
connectionmanager_get_protocol_info_action_connect (GUPnPService *service,
                                                    GCallback callback,
                                                    gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetProtocolInfo",
                           callback,
                           userdata);
}


/* action PrepareForConnection */

static inline void
connectionmanager_prepare_for_connection_action_get (GUPnPServiceAction *action,
                                                     gchar **in_remote_protocol_info,
                                                     gchar **in_peer_connection_manager,
                                                     gint *in_peer_connection_id,
                                                     gchar **in_direction)
{
  gupnp_service_action_get (action,
                            "RemoteProtocolInfo", G_TYPE_STRING, in_remote_protocol_info,
                            "PeerConnectionManager", G_TYPE_STRING, in_peer_connection_manager,
                            "PeerConnectionID", G_TYPE_INT, in_peer_connection_id,
                            "Direction", G_TYPE_STRING, in_direction,
                            NULL);
}

static inline void
connectionmanager_prepare_for_connection_action_set (GUPnPServiceAction *action,
                                                     const gint out_connection_id,
                                                     const gint out_av_transport_id,
                                                     const gint out_rcs_id)
{
  gupnp_service_action_set (action,
                            "ConnectionID", G_TYPE_INT, out_connection_id,
                            "AVTransportID", G_TYPE_INT, out_av_transport_id,
                            "RcsID", G_TYPE_INT, out_rcs_id,
                            NULL);
}

static inline gulong
connectionmanager_prepare_for_connection_action_connect (GUPnPService *service,
                                                         GCallback callback,
                                                         gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::PrepareForConnection",
                           callback,
                           userdata);
}


/* action ConnectionComplete */

static inline void
connectionmanager_connection_complete_action_get (GUPnPServiceAction *action,
                                                  gint *in_connection_id)
{
  gupnp_service_action_get (action,
                            "ConnectionID", G_TYPE_INT, in_connection_id,
                            NULL);
}

static inline gulong
connectionmanager_connection_complete_action_connect (GUPnPService *service,
                                                      GCallback callback,
                                                      gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::ConnectionComplete",
                           callback,
                           userdata);
}


/* action GetCurrentConnectionIDs */

static inline void
connectionmanager_get_current_connection_i_ds_action_set (GUPnPServiceAction *action,
                                                          const gchar *out_connection_i_ds)
{
  gupnp_service_action_set (action,
                            "ConnectionIDs", G_TYPE_STRING, out_connection_i_ds,
                            NULL);
}

static inline gulong
connectionmanager_get_current_connection_i_ds_action_connect (GUPnPService *service,
                                                              GCallback callback,
                                                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetCurrentConnectionIDs",
                           callback,
                           userdata);
}


/* action GetCurrentConnectionInfo */

static inline void
connectionmanager_get_current_connection_info_action_get (GUPnPServiceAction *action,
                                                          gint *in_connection_id)
{
  gupnp_service_action_get (action,
                            "ConnectionID", G_TYPE_INT, in_connection_id,
                            NULL);
}

static inline void
connectionmanager_get_current_connection_info_action_set (GUPnPServiceAction *action,
                                                          const gint out_rcs_id,
                                                          const gint out_av_transport_id,
                                                          const gchar *out_protocol_info,
                                                          const gchar *out_peer_connection_manager,
                                                          const gint out_peer_connection_id,
                                                          const gchar *out_direction,
                                                          const gchar *out_status)
{
  gupnp_service_action_set (action,
                            "RcsID", G_TYPE_INT, out_rcs_id,
                            "AVTransportID", G_TYPE_INT, out_av_transport_id,
                            "ProtocolInfo", G_TYPE_STRING, out_protocol_info,
                            "PeerConnectionManager", G_TYPE_STRING, out_peer_connection_manager,
                            "PeerConnectionID", G_TYPE_INT, out_peer_connection_id,
                            "Direction", G_TYPE_STRING, out_direction,
                            "Status", G_TYPE_STRING, out_status,
                            NULL);
}

static inline gulong
connectionmanager_get_current_connection_info_action_connect (GUPnPService *service,
                                                              GCallback callback,
                                                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetCurrentConnectionInfo",
                           callback,
                           userdata);
}


/* state variable SourceProtocolInfo */

typedef gchar *(*connectionmanager_source_protocol_info_query_callback) (GUPnPService *service,
                                                                         gpointer userdata);

static void
_connectionmanager_source_protocol_info_query_cb (GUPnPService *service,
                                                  gchar *variable,
                                                  GValue *value,
                                                  gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *source_protocol_info;

  cbdata = (GUPnPAsyncData *) userdata;
  source_protocol_info = ((connectionmanager_source_protocol_info_query_callback)cbdata->cb) (service,
                                                                                              cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, source_protocol_info);
}

gulong
connectionmanager_source_protocol_info_query_connect (GUPnPService *service,
                                                      connectionmanager_source_protocol_info_query_callback callback,
                                                      gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::SourceProtocolInfo",
                                G_CALLBACK (_connectionmanager_source_protocol_info_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}

void
connectionmanager_source_protocol_info_variable_notify (GUPnPService *service,
                                                        const gchar *source_protocol_info)
{
  gupnp_service_notify (service,
                        "SourceProtocolInfo", G_TYPE_STRING, source_protocol_info,
                        NULL);
}


/* state variable SinkProtocolInfo */

typedef gchar *(*connectionmanager_sink_protocol_info_query_callback) (GUPnPService *service,
                                                                       gpointer userdata);

static void
_connectionmanager_sink_protocol_info_query_cb (GUPnPService *service,
                                                gchar *variable,
                                                GValue *value,
                                                gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *sink_protocol_info;

  cbdata = (GUPnPAsyncData *) userdata;
  sink_protocol_info = ((connectionmanager_sink_protocol_info_query_callback)cbdata->cb) (service,
                                                                                          cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, sink_protocol_info);
}

gulong
connectionmanager_sink_protocol_info_query_connect (GUPnPService *service,
                                                    connectionmanager_sink_protocol_info_query_callback callback,
                                                    gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::SinkProtocolInfo",
                                G_CALLBACK (_connectionmanager_sink_protocol_info_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}

void
connectionmanager_sink_protocol_info_variable_notify (GUPnPService *service,
                                                      const gchar *sink_protocol_info)
{
  gupnp_service_notify (service,
                        "SinkProtocolInfo", G_TYPE_STRING, sink_protocol_info,
                        NULL);
}


/* state variable CurrentConnectionIDs */

typedef gchar *(*connectionmanager_current_connection_i_ds_query_callback) (GUPnPService *service,
                                                                            gpointer userdata);

static void
_connectionmanager_current_connection_i_ds_query_cb (GUPnPService *service,
                                                     gchar *variable,
                                                     GValue *value,
                                                     gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *current_connection_i_ds;

  cbdata = (GUPnPAsyncData *) userdata;
  current_connection_i_ds = ((connectionmanager_current_connection_i_ds_query_callback)cbdata->cb) (service,
                                                                                                    cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, current_connection_i_ds);
}

gulong
connectionmanager_current_connection_i_ds_query_connect (GUPnPService *service,
                                                         connectionmanager_current_connection_i_ds_query_callback callback,
                                                         gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::CurrentConnectionIDs",
                                G_CALLBACK (_connectionmanager_current_connection_i_ds_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}

void
connectionmanager_current_connection_i_ds_variable_notify (GUPnPService *service,
                                                           const gchar *current_connection_i_ds)
{
  gupnp_service_notify (service,
                        "CurrentConnectionIDs", G_TYPE_STRING, current_connection_i_ds,
                        NULL);
}


G_END_DECLS

#endif /* GUPNP_GENERATED_CLIENT_BINDING_CONNECTIONMANAGER */
