#include "gstreamer.h"
#include <stdlib.h>
#include <stdio.h>

static GString *mime_types=NULL;
static gchar *playing_uri=NULL;
time_t play_time=0;
time_t pause_time=0;
static char *readfile(char *fname,int *fsize)
{
 FILE *fp;
 unsigned long size,lsize;
 char *pt;
 int len;
 char buf[100];

 size=0;
 pt=NULL;
 fp=fopen(fname,"r");
 if (!fp) return NULL;
 while (1)
  {
   len=fread(buf,1,100,fp); 
   if (len==-1)
    goto sysfail;
   lsize=size;
   size+=len;
   pt=(char *)realloc(pt,size+1);
   if (len==0)
    {
     pt[size]='\0';
     break;
    }
   if (!pt)
    goto sysfail;
   memcpy(pt+lsize,buf,len);
  }
 fclose(fp);
 pt[size]='\0';
 *fsize=size;
 return pt;

sysfail:
 fclose(fp);
 if (pt)
  free(pt);
 return NULL;
}

GString*
gstreamer_format_time (gint64 time)
{
    gchar value[30];
    sprintf(value, "00:%02u:%02u.%02u", (unsigned int)time/60, (unsigned int)time%60, (unsigned int)(time*100)%100);
    return g_string_new(value);
}

void
gstreamer_print_uri (const char *prefix)
{
    g_debug("%s: %s", prefix, playing_uri);
}

void 
gstreamer_set_uri (gchar *uri)
{
    playing_uri = strdup(uri);
    gstreamer_print_uri ("location");
}

void
gstreamer_play ()
{
    FILE *fp;
    char cmd_buf[512];
    char play_pid[10];
    gstreamer_print_uri ("play");
    if(play_time==0)
    {   
    	unlink("/tmp/iradio");
    	system("killall -9 asplayer");
    	system("killall mDNSPublish");
    	system("killall shairport");
    	play_time=time(NULL);
    	sprintf(cmd_buf,"asplayer --m3player %s&", playing_uri);
    	system(cmd_buf);
    }
    else
    {	//after pause

       if(pause_time)
       {	  
 	   	fp = fopen("/var/run/asplayer.pid", "r"); 
    		if(fp != NULL){
			 fgets(play_pid,10,fp);
			 fclose(fp);
	   	 }
	       	sprintf(cmd_buf,"kill -SIGUSR1 %d",atoi(play_pid));
	        system(cmd_buf);	
		play_time+=(time(NULL)-pause_time);
    	}
   //	else
   //		printf("twice play\n");
    }
    pause_time=0;
}

void
gstreamer_pause ()
{
    char cmd_buf[512];
    char play_pid[10];
    FILE *fp;

    if(pause_time==0)
    {   
	    fp = fopen("/var/run/asplayer.pid", "r"); 
	    if(fp != NULL){
	       fgets(play_pid,10,fp);
	       fclose(fp);
	    }
	    gstreamer_print_uri ("pause");
	    pause_time=time(NULL);
	    sprintf(cmd_buf,"kill -SIGUSR1 %d",atoi(play_pid));
	    system(cmd_buf);
     }
    // else
    //	printf("twice pause\n");
}

void
gstreamer_stop ()
{
    gstreamer_print_uri ("stop");

    if(play_time)
     {
#ifdef LED_INDICATE_AUDIO_PLAY
      nvram_set("audio_playing", "0");
#endif
      system("killall -9 asplayer");
      play_time=0;
     }
}

gboolean
gstreamer_get_element_info (gint64 *position, gint64 *duration)
{
    time_t cur_time;
    char *pt;
    int fsize;
    if(!pause_time)
	cur_time=time(NULL);
    else
       cur_time=pause_time;

    pt=readfile("/tmp/duration.txt", &fsize); // generated by asplayer
    if (pt)
    {
      *duration=atol(pt);
      free(pt);
    }
    else
      *duration=0;

    pt=readfile("/tmp/position.txt", &fsize); // generated by asplayer
    if (pt)
    {
      *position=atol(pt);
      free(pt);
    }
    else
     *position=cur_time-play_time;

    return TRUE;
}

const char*
gstreamer_get_mime_types ()
{
    return mime_types->str;
}

GString*
gstreamer_find_mime_types ()
{
    GString *mt_str = g_string_new ("http-get:*:audio/mpeg:*,http-get:*:audio/x-iec958:*,http-get:*:audio/x-raw-int:*,http-get:*:audio/x-flac:*,http-get:*:audio/x-wav:*,http-get:*:audio/x-wma:*");
    g_debug ("mime-types: %s", mt_str->str);

    return mt_str;
}

void
gstreamer_init (GMainLoop *main_loop)
{
    mime_types = gstreamer_find_mime_types ();
}

void
gstreamer_cleanup ()
{
    if (mime_types)
      g_string_free (mime_types, TRUE);
    if (playing_uri)
      free(playing_uri);

    if(play_time)
     {
      system("killall -9 asplayer");
      play_time=0;
     }
}
