/* Generated by gupnp-binding-tool */

#include <libgupnp/gupnp.h>

#ifndef GUPNP_GENERATED_CLIENT_BINDING_RENDERINGCONTROL
#define GUPNP_GENERATED_CLIENT_BINDING_RENDERINGCONTROL

G_BEGIN_DECLS

#ifndef __GUPNPASYNCDATA_TYPE__
#define __GUPNPASYNCDATA_TYPE__
typedef struct {GCallback cb; gpointer userdata; } GUPnPAsyncData;
#endif
static void
_free_cb_data (gpointer data, GClosure *closure)
{
  GUPnPAsyncData *cbdata = (GUPnPAsyncData *) data;
  g_slice_free1 (sizeof (*cbdata), cbdata);
}


/* action ListPresets */

static inline void
renderingcontrol_list_presets_action_get (GUPnPServiceAction *action,
                                          guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_list_presets_action_set (GUPnPServiceAction *action,
                                          const gchar *out_current_preset_name_list)
{
  gupnp_service_action_set (action,
                            "CurrentPresetNameList", G_TYPE_STRING, out_current_preset_name_list,
                            NULL);
}

static inline gulong
renderingcontrol_list_presets_action_connect (GUPnPService *service,
                                              GCallback callback,
                                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::ListPresets",
                           callback,
                           userdata);
}


/* action SelectPreset */

static inline void
renderingcontrol_select_preset_action_get (GUPnPServiceAction *action,
                                           guint *in_instance_id,
                                           gchar **in_preset_name)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "PresetName", G_TYPE_STRING, in_preset_name,
                            NULL);
}

static inline gulong
renderingcontrol_select_preset_action_connect (GUPnPService *service,
                                               GCallback callback,
                                               gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SelectPreset",
                           callback,
                           userdata);
}


/* action GetBrightness */

static inline void
renderingcontrol_get_brightness_action_get (GUPnPServiceAction *action,
                                            guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_brightness_action_set (GUPnPServiceAction *action,
                                            const guint out_current_brightness)
{
  gupnp_service_action_set (action,
                            "CurrentBrightness", G_TYPE_UINT, out_current_brightness,
                            NULL);
}

static inline gulong
renderingcontrol_get_brightness_action_connect (GUPnPService *service,
                                                GCallback callback,
                                                gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetBrightness",
                           callback,
                           userdata);
}


/* action SetBrightness */

static inline void
renderingcontrol_set_brightness_action_get (GUPnPServiceAction *action,
                                            guint *in_instance_id,
                                            guint *in_desired_brightness)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredBrightness", G_TYPE_UINT, in_desired_brightness,
                            NULL);
}

static inline gulong
renderingcontrol_set_brightness_action_connect (GUPnPService *service,
                                                GCallback callback,
                                                gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetBrightness",
                           callback,
                           userdata);
}


/* action GetContrast */

static inline void
renderingcontrol_get_contrast_action_get (GUPnPServiceAction *action,
                                          guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_contrast_action_set (GUPnPServiceAction *action,
                                          const guint out_current_contrast)
{
  gupnp_service_action_set (action,
                            "CurrentContrast", G_TYPE_UINT, out_current_contrast,
                            NULL);
}

static inline gulong
renderingcontrol_get_contrast_action_connect (GUPnPService *service,
                                              GCallback callback,
                                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetContrast",
                           callback,
                           userdata);
}


/* action SetContrast */

static inline void
renderingcontrol_set_contrast_action_get (GUPnPServiceAction *action,
                                          guint *in_instance_id,
                                          guint *in_desired_contrast)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredContrast", G_TYPE_UINT, in_desired_contrast,
                            NULL);
}

static inline gulong
renderingcontrol_set_contrast_action_connect (GUPnPService *service,
                                              GCallback callback,
                                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetContrast",
                           callback,
                           userdata);
}


/* action GetSharpness */

static inline void
renderingcontrol_get_sharpness_action_get (GUPnPServiceAction *action,
                                           guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_sharpness_action_set (GUPnPServiceAction *action,
                                           const guint out_current_sharpness)
{
  gupnp_service_action_set (action,
                            "CurrentSharpness", G_TYPE_UINT, out_current_sharpness,
                            NULL);
}

static inline gulong
renderingcontrol_get_sharpness_action_connect (GUPnPService *service,
                                               GCallback callback,
                                               gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetSharpness",
                           callback,
                           userdata);
}


/* action SetSharpness */

static inline void
renderingcontrol_set_sharpness_action_get (GUPnPServiceAction *action,
                                           guint *in_instance_id,
                                           guint *in_desired_sharpness)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredSharpness", G_TYPE_UINT, in_desired_sharpness,
                            NULL);
}

static inline gulong
renderingcontrol_set_sharpness_action_connect (GUPnPService *service,
                                               GCallback callback,
                                               gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetSharpness",
                           callback,
                           userdata);
}


/* action GetRedVideoGain */

static inline void
renderingcontrol_get_red_video_gain_action_get (GUPnPServiceAction *action,
                                                guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_red_video_gain_action_set (GUPnPServiceAction *action,
                                                const guint out_current_red_video_gain)
{
  gupnp_service_action_set (action,
                            "CurrentRedVideoGain", G_TYPE_UINT, out_current_red_video_gain,
                            NULL);
}

static inline gulong
renderingcontrol_get_red_video_gain_action_connect (GUPnPService *service,
                                                    GCallback callback,
                                                    gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetRedVideoGain",
                           callback,
                           userdata);
}


/* action SetRedVideoGain */

static inline void
renderingcontrol_set_red_video_gain_action_get (GUPnPServiceAction *action,
                                                guint *in_instance_id,
                                                guint *in_desired_red_video_gain)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredRedVideoGain", G_TYPE_UINT, in_desired_red_video_gain,
                            NULL);
}

static inline gulong
renderingcontrol_set_red_video_gain_action_connect (GUPnPService *service,
                                                    GCallback callback,
                                                    gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetRedVideoGain",
                           callback,
                           userdata);
}


/* action GetGreenVideoGain */

static inline void
renderingcontrol_get_green_video_gain_action_get (GUPnPServiceAction *action,
                                                  guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_green_video_gain_action_set (GUPnPServiceAction *action,
                                                  const guint out_current_green_video_gain)
{
  gupnp_service_action_set (action,
                            "CurrentGreenVideoGain", G_TYPE_UINT, out_current_green_video_gain,
                            NULL);
}

static inline gulong
renderingcontrol_get_green_video_gain_action_connect (GUPnPService *service,
                                                      GCallback callback,
                                                      gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetGreenVideoGain",
                           callback,
                           userdata);
}


/* action SetGreenVideoGain */

static inline void
renderingcontrol_set_green_video_gain_action_get (GUPnPServiceAction *action,
                                                  guint *in_instance_id,
                                                  guint *in_desired_green_video_gain)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredGreenVideoGain", G_TYPE_UINT, in_desired_green_video_gain,
                            NULL);
}

static inline gulong
renderingcontrol_set_green_video_gain_action_connect (GUPnPService *service,
                                                      GCallback callback,
                                                      gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetGreenVideoGain",
                           callback,
                           userdata);
}


/* action GetBlueVideoGain */

static inline void
renderingcontrol_get_blue_video_gain_action_get (GUPnPServiceAction *action,
                                                 guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_blue_video_gain_action_set (GUPnPServiceAction *action,
                                                 const guint out_current_blue_video_gain)
{
  gupnp_service_action_set (action,
                            "CurrentBlueVideoGain", G_TYPE_UINT, out_current_blue_video_gain,
                            NULL);
}

static inline gulong
renderingcontrol_get_blue_video_gain_action_connect (GUPnPService *service,
                                                     GCallback callback,
                                                     gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetBlueVideoGain",
                           callback,
                           userdata);
}


/* action SetBlueVideoGain */

static inline void
renderingcontrol_set_blue_video_gain_action_get (GUPnPServiceAction *action,
                                                 guint *in_instance_id,
                                                 guint *in_desired_blue_video_gain)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredBlueVideoGain", G_TYPE_UINT, in_desired_blue_video_gain,
                            NULL);
}

static inline gulong
renderingcontrol_set_blue_video_gain_action_connect (GUPnPService *service,
                                                     GCallback callback,
                                                     gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetBlueVideoGain",
                           callback,
                           userdata);
}


/* action GetRedVideoBlackLevel */

static inline void
renderingcontrol_get_red_video_black_level_action_get (GUPnPServiceAction *action,
                                                       guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_red_video_black_level_action_set (GUPnPServiceAction *action,
                                                       const guint out_current_red_video_black_level)
{
  gupnp_service_action_set (action,
                            "CurrentRedVideoBlackLevel", G_TYPE_UINT, out_current_red_video_black_level,
                            NULL);
}

static inline gulong
renderingcontrol_get_red_video_black_level_action_connect (GUPnPService *service,
                                                           GCallback callback,
                                                           gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetRedVideoBlackLevel",
                           callback,
                           userdata);
}


/* action SetRedVideoBlackLevel */

static inline void
renderingcontrol_set_red_video_black_level_action_get (GUPnPServiceAction *action,
                                                       guint *in_instance_id,
                                                       guint *in_desired_red_video_black_level)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredRedVideoBlackLevel", G_TYPE_UINT, in_desired_red_video_black_level,
                            NULL);
}

static inline gulong
renderingcontrol_set_red_video_black_level_action_connect (GUPnPService *service,
                                                           GCallback callback,
                                                           gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetRedVideoBlackLevel",
                           callback,
                           userdata);
}


/* action GetGreenVideoBlackLevel */

static inline void
renderingcontrol_get_green_video_black_level_action_get (GUPnPServiceAction *action,
                                                         guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_green_video_black_level_action_set (GUPnPServiceAction *action,
                                                         const guint out_current_green_video_black_level)
{
  gupnp_service_action_set (action,
                            "CurrentGreenVideoBlackLevel", G_TYPE_UINT, out_current_green_video_black_level,
                            NULL);
}

static inline gulong
renderingcontrol_get_green_video_black_level_action_connect (GUPnPService *service,
                                                             GCallback callback,
                                                             gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetGreenVideoBlackLevel",
                           callback,
                           userdata);
}


/* action SetGreenVideoBlackLevel */

static inline void
renderingcontrol_set_green_video_black_level_action_get (GUPnPServiceAction *action,
                                                         guint *in_instance_id,
                                                         guint *in_desired_green_video_black_level)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredGreenVideoBlackLevel", G_TYPE_UINT, in_desired_green_video_black_level,
                            NULL);
}

static inline gulong
renderingcontrol_set_green_video_black_level_action_connect (GUPnPService *service,
                                                             GCallback callback,
                                                             gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetGreenVideoBlackLevel",
                           callback,
                           userdata);
}


/* action GetBlueVideoBlackLevel */

static inline void
renderingcontrol_get_blue_video_black_level_action_get (GUPnPServiceAction *action,
                                                        guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_blue_video_black_level_action_set (GUPnPServiceAction *action,
                                                        const guint out_current_blue_video_black_level)
{
  gupnp_service_action_set (action,
                            "CurrentBlueVideoBlackLevel", G_TYPE_UINT, out_current_blue_video_black_level,
                            NULL);
}

static inline gulong
renderingcontrol_get_blue_video_black_level_action_connect (GUPnPService *service,
                                                            GCallback callback,
                                                            gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetBlueVideoBlackLevel",
                           callback,
                           userdata);
}


/* action SetBlueVideoBlackLevel */

static inline void
renderingcontrol_set_blue_video_black_level_action_get (GUPnPServiceAction *action,
                                                        guint *in_instance_id,
                                                        guint *in_desired_blue_video_black_level)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredBlueVideoBlackLevel", G_TYPE_UINT, in_desired_blue_video_black_level,
                            NULL);
}

static inline gulong
renderingcontrol_set_blue_video_black_level_action_connect (GUPnPService *service,
                                                            GCallback callback,
                                                            gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetBlueVideoBlackLevel",
                           callback,
                           userdata);
}


/* action GetColorTemperature */

static inline void
renderingcontrol_get_color_temperature_action_get (GUPnPServiceAction *action,
                                                   guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_color_temperature_action_set (GUPnPServiceAction *action,
                                                   const guint out_current_color_temperature)
{
  gupnp_service_action_set (action,
                            "CurrentColorTemperature", G_TYPE_UINT, out_current_color_temperature,
                            NULL);
}

static inline gulong
renderingcontrol_get_color_temperature_action_connect (GUPnPService *service,
                                                       GCallback callback,
                                                       gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetColorTemperature",
                           callback,
                           userdata);
}


/* action SetColorTemperature */

static inline void
renderingcontrol_set_color_temperature_action_get (GUPnPServiceAction *action,
                                                   guint *in_instance_id,
                                                   guint *in_desired_color_temperature)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredColorTemperature", G_TYPE_UINT, in_desired_color_temperature,
                            NULL);
}

static inline gulong
renderingcontrol_set_color_temperature_action_connect (GUPnPService *service,
                                                       GCallback callback,
                                                       gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetColorTemperature",
                           callback,
                           userdata);
}


/* action GetHorizontalKeystone */

static inline void
renderingcontrol_get_horizontal_keystone_action_get (GUPnPServiceAction *action,
                                                     guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_horizontal_keystone_action_set (GUPnPServiceAction *action,
                                                     const gint out_current_horizontal_keystone)
{
  gupnp_service_action_set (action,
                            "CurrentHorizontalKeystone", G_TYPE_INT, out_current_horizontal_keystone,
                            NULL);
}

static inline gulong
renderingcontrol_get_horizontal_keystone_action_connect (GUPnPService *service,
                                                         GCallback callback,
                                                         gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetHorizontalKeystone",
                           callback,
                           userdata);
}


/* action SetHorizontalKeystone */

static inline void
renderingcontrol_set_horizontal_keystone_action_get (GUPnPServiceAction *action,
                                                     guint *in_instance_id,
                                                     gint *in_desired_horizontal_keystone)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredHorizontalKeystone", G_TYPE_INT, in_desired_horizontal_keystone,
                            NULL);
}

static inline gulong
renderingcontrol_set_horizontal_keystone_action_connect (GUPnPService *service,
                                                         GCallback callback,
                                                         gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetHorizontalKeystone",
                           callback,
                           userdata);
}


/* action GetVerticalKeystone */

static inline void
renderingcontrol_get_vertical_keystone_action_get (GUPnPServiceAction *action,
                                                   guint *in_instance_id)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            NULL);
}

static inline void
renderingcontrol_get_vertical_keystone_action_set (GUPnPServiceAction *action,
                                                   const gint out_current_vertical_keystone)
{
  gupnp_service_action_set (action,
                            "CurrentVerticalKeystone", G_TYPE_INT, out_current_vertical_keystone,
                            NULL);
}

static inline gulong
renderingcontrol_get_vertical_keystone_action_connect (GUPnPService *service,
                                                       GCallback callback,
                                                       gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetVerticalKeystone",
                           callback,
                           userdata);
}


/* action SetVerticalKeystone */

static inline void
renderingcontrol_set_vertical_keystone_action_get (GUPnPServiceAction *action,
                                                   guint *in_instance_id,
                                                   gint *in_desired_vertical_keystone)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "DesiredVerticalKeystone", G_TYPE_INT, in_desired_vertical_keystone,
                            NULL);
}

static inline gulong
renderingcontrol_set_vertical_keystone_action_connect (GUPnPService *service,
                                                       GCallback callback,
                                                       gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetVerticalKeystone",
                           callback,
                           userdata);
}


/* action GetMute */

static inline void
renderingcontrol_get_mute_action_get (GUPnPServiceAction *action,
                                      guint *in_instance_id,
                                      gchar **in_channel)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            NULL);
}

static inline void
renderingcontrol_get_mute_action_set (GUPnPServiceAction *action,
                                      const gboolean out_current_mute)
{
  gupnp_service_action_set (action,
                            "CurrentMute", G_TYPE_BOOLEAN, out_current_mute,
                            NULL);
}

static inline gulong
renderingcontrol_get_mute_action_connect (GUPnPService *service,
                                          GCallback callback,
                                          gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetMute",
                           callback,
                           userdata);
}


/* action SetMute */

static inline void
renderingcontrol_set_mute_action_get (GUPnPServiceAction *action,
                                      guint *in_instance_id,
                                      gchar **in_channel,
                                      gboolean *in_desired_mute)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            "DesiredMute", G_TYPE_BOOLEAN, in_desired_mute,
                            NULL);
}

static inline gulong
renderingcontrol_set_mute_action_connect (GUPnPService *service,
                                          GCallback callback,
                                          gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetMute",
                           callback,
                           userdata);
}


/* action GetVolume */

static inline void
renderingcontrol_get_volume_action_get (GUPnPServiceAction *action,
                                        guint *in_instance_id,
                                        gchar **in_channel)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            NULL);
}

static inline void
renderingcontrol_get_volume_action_set (GUPnPServiceAction *action,
                                        const guint out_current_volume)
{
  gupnp_service_action_set (action,
                            "CurrentVolume", G_TYPE_UINT, out_current_volume,
                            NULL);
}

static inline gulong
renderingcontrol_get_volume_action_connect (GUPnPService *service,
                                            GCallback callback,
                                            gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetVolume",
                           callback,
                           userdata);
}


/* action SetVolume */

static inline void
renderingcontrol_set_volume_action_get (GUPnPServiceAction *action,
                                        guint *in_instance_id,
                                        gchar **in_channel,
                                        guint *in_desired_volume)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            "DesiredVolume", G_TYPE_UINT, in_desired_volume,
                            NULL);
}

static inline gulong
renderingcontrol_set_volume_action_connect (GUPnPService *service,
                                            GCallback callback,
                                            gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetVolume",
                           callback,
                           userdata);
}


/* action GetVolumeDB */

static inline void
renderingcontrol_get_volume_db_action_get (GUPnPServiceAction *action,
                                           guint *in_instance_id,
                                           gchar **in_channel)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            NULL);
}

static inline void
renderingcontrol_get_volume_db_action_set (GUPnPServiceAction *action,
                                           const gint out_current_volume)
{
  gupnp_service_action_set (action,
                            "CurrentVolume", G_TYPE_INT, out_current_volume,
                            NULL);
}

static inline gulong
renderingcontrol_get_volume_db_action_connect (GUPnPService *service,
                                               GCallback callback,
                                               gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetVolumeDB",
                           callback,
                           userdata);
}


/* action SetVolumeDB */

static inline void
renderingcontrol_set_volume_db_action_get (GUPnPServiceAction *action,
                                           guint *in_instance_id,
                                           gchar **in_channel,
                                           gint *in_desired_volume)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            "DesiredVolume", G_TYPE_INT, in_desired_volume,
                            NULL);
}

static inline gulong
renderingcontrol_set_volume_db_action_connect (GUPnPService *service,
                                               GCallback callback,
                                               gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetVolumeDB",
                           callback,
                           userdata);
}


/* action GetVolumeDBRange */

static inline void
renderingcontrol_get_volume_db_range_action_get (GUPnPServiceAction *action,
                                                 guint *in_instance_id,
                                                 gchar **in_channel)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            NULL);
}

static inline void
renderingcontrol_get_volume_db_range_action_set (GUPnPServiceAction *action,
                                                 const gint out_min_value,
                                                 const gint out_max_value)
{
  gupnp_service_action_set (action,
                            "MinValue", G_TYPE_INT, out_min_value,
                            "MaxValue", G_TYPE_INT, out_max_value,
                            NULL);
}

static inline gulong
renderingcontrol_get_volume_db_range_action_connect (GUPnPService *service,
                                                     GCallback callback,
                                                     gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetVolumeDBRange",
                           callback,
                           userdata);
}


/* action GetLoudness */

static inline void
renderingcontrol_get_loudness_action_get (GUPnPServiceAction *action,
                                          guint *in_instance_id,
                                          gchar **in_channel)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            NULL);
}

static inline void
renderingcontrol_get_loudness_action_set (GUPnPServiceAction *action,
                                          const gboolean out_current_loudness)
{
  gupnp_service_action_set (action,
                            "CurrentLoudness", G_TYPE_BOOLEAN, out_current_loudness,
                            NULL);
}

static inline gulong
renderingcontrol_get_loudness_action_connect (GUPnPService *service,
                                              GCallback callback,
                                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::GetLoudness",
                           callback,
                           userdata);
}


/* action SetLoudness */

static inline void
renderingcontrol_set_loudness_action_get (GUPnPServiceAction *action,
                                          guint *in_instance_id,
                                          gchar **in_channel,
                                          gboolean *in_desired_loudness)
{
  gupnp_service_action_get (action,
                            "InstanceID", G_TYPE_UINT, in_instance_id,
                            "Channel", G_TYPE_STRING, in_channel,
                            "DesiredLoudness", G_TYPE_BOOLEAN, in_desired_loudness,
                            NULL);
}

static inline gulong
renderingcontrol_set_loudness_action_connect (GUPnPService *service,
                                              GCallback callback,
                                              gpointer userdata)
{
  return g_signal_connect (service,
                           "action-invoked::SetLoudness",
                           callback,
                           userdata);
}


/* state variable PresetNameList */

typedef gchar *(*renderingcontrol_preset_name_list_query_callback) (GUPnPService *service,
                                                                    gpointer userdata);

static void
_renderingcontrol_preset_name_list_query_cb (GUPnPService *service,
                                             gchar *variable,
                                             GValue *value,
                                             gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *preset_name_list;

  cbdata = (GUPnPAsyncData *) userdata;
  preset_name_list = ((renderingcontrol_preset_name_list_query_callback)cbdata->cb) (service,
                                                                                     cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, preset_name_list);
}

gulong
renderingcontrol_preset_name_list_query_connect (GUPnPService *service,
                                                 renderingcontrol_preset_name_list_query_callback callback,
                                                 gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::PresetNameList",
                                G_CALLBACK (_renderingcontrol_preset_name_list_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable LastChange */

typedef gchar *(*renderingcontrol_last_change_query_callback) (GUPnPService *service,
                                                               gpointer userdata);

static void
_renderingcontrol_last_change_query_cb (GUPnPService *service,
                                        gchar *variable,
                                        GValue *value,
                                        gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gchar *last_change;

  cbdata = (GUPnPAsyncData *) userdata;
  last_change = ((renderingcontrol_last_change_query_callback)cbdata->cb) (service,
                                                                           cbdata->userdata);
  g_value_init (value, G_TYPE_STRING);
  g_value_set_string (value, last_change);
}

gulong
renderingcontrol_last_change_query_connect (GUPnPService *service,
                                            renderingcontrol_last_change_query_callback callback,
                                            gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::LastChange",
                                G_CALLBACK (_renderingcontrol_last_change_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}

void
renderingcontrol_last_change_variable_notify (GUPnPService *service,
                                              const gchar *last_change)
{
  gupnp_service_notify (service,
                        "LastChange", G_TYPE_STRING, last_change,
                        NULL);
}


/* state variable Brightness */

typedef guint (*renderingcontrol_brightness_query_callback) (GUPnPService *service,
                                                             gpointer userdata);

static void
_renderingcontrol_brightness_query_cb (GUPnPService *service,
                                       gchar *variable,
                                       GValue *value,
                                       gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint brightness;

  cbdata = (GUPnPAsyncData *) userdata;
  brightness = ((renderingcontrol_brightness_query_callback)cbdata->cb) (service,
                                                                         cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, brightness);
}

gulong
renderingcontrol_brightness_query_connect (GUPnPService *service,
                                           renderingcontrol_brightness_query_callback callback,
                                           gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::Brightness",
                                G_CALLBACK (_renderingcontrol_brightness_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable Contrast */

typedef guint (*renderingcontrol_contrast_query_callback) (GUPnPService *service,
                                                           gpointer userdata);

static void
_renderingcontrol_contrast_query_cb (GUPnPService *service,
                                     gchar *variable,
                                     GValue *value,
                                     gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint contrast;

  cbdata = (GUPnPAsyncData *) userdata;
  contrast = ((renderingcontrol_contrast_query_callback)cbdata->cb) (service,
                                                                     cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, contrast);
}

gulong
renderingcontrol_contrast_query_connect (GUPnPService *service,
                                         renderingcontrol_contrast_query_callback callback,
                                         gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::Contrast",
                                G_CALLBACK (_renderingcontrol_contrast_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable Sharpness */

typedef guint (*renderingcontrol_sharpness_query_callback) (GUPnPService *service,
                                                            gpointer userdata);

static void
_renderingcontrol_sharpness_query_cb (GUPnPService *service,
                                      gchar *variable,
                                      GValue *value,
                                      gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint sharpness;

  cbdata = (GUPnPAsyncData *) userdata;
  sharpness = ((renderingcontrol_sharpness_query_callback)cbdata->cb) (service,
                                                                       cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, sharpness);
}

gulong
renderingcontrol_sharpness_query_connect (GUPnPService *service,
                                          renderingcontrol_sharpness_query_callback callback,
                                          gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::Sharpness",
                                G_CALLBACK (_renderingcontrol_sharpness_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable RedVideoGain */

typedef guint (*renderingcontrol_red_video_gain_query_callback) (GUPnPService *service,
                                                                 gpointer userdata);

static void
_renderingcontrol_red_video_gain_query_cb (GUPnPService *service,
                                           gchar *variable,
                                           GValue *value,
                                           gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint red_video_gain;

  cbdata = (GUPnPAsyncData *) userdata;
  red_video_gain = ((renderingcontrol_red_video_gain_query_callback)cbdata->cb) (service,
                                                                                 cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, red_video_gain);
}

gulong
renderingcontrol_red_video_gain_query_connect (GUPnPService *service,
                                               renderingcontrol_red_video_gain_query_callback callback,
                                               gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::RedVideoGain",
                                G_CALLBACK (_renderingcontrol_red_video_gain_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable GreenVideoGain */

typedef guint (*renderingcontrol_green_video_gain_query_callback) (GUPnPService *service,
                                                                   gpointer userdata);

static void
_renderingcontrol_green_video_gain_query_cb (GUPnPService *service,
                                             gchar *variable,
                                             GValue *value,
                                             gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint green_video_gain;

  cbdata = (GUPnPAsyncData *) userdata;
  green_video_gain = ((renderingcontrol_green_video_gain_query_callback)cbdata->cb) (service,
                                                                                     cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, green_video_gain);
}

gulong
renderingcontrol_green_video_gain_query_connect (GUPnPService *service,
                                                 renderingcontrol_green_video_gain_query_callback callback,
                                                 gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::GreenVideoGain",
                                G_CALLBACK (_renderingcontrol_green_video_gain_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable BlueVideoGain */

typedef guint (*renderingcontrol_blue_video_gain_query_callback) (GUPnPService *service,
                                                                  gpointer userdata);

static void
_renderingcontrol_blue_video_gain_query_cb (GUPnPService *service,
                                            gchar *variable,
                                            GValue *value,
                                            gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint blue_video_gain;

  cbdata = (GUPnPAsyncData *) userdata;
  blue_video_gain = ((renderingcontrol_blue_video_gain_query_callback)cbdata->cb) (service,
                                                                                   cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, blue_video_gain);
}

gulong
renderingcontrol_blue_video_gain_query_connect (GUPnPService *service,
                                                renderingcontrol_blue_video_gain_query_callback callback,
                                                gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::BlueVideoGain",
                                G_CALLBACK (_renderingcontrol_blue_video_gain_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable RedVideoBlackLevel */

typedef guint (*renderingcontrol_red_video_black_level_query_callback) (GUPnPService *service,
                                                                        gpointer userdata);

static void
_renderingcontrol_red_video_black_level_query_cb (GUPnPService *service,
                                                  gchar *variable,
                                                  GValue *value,
                                                  gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint red_video_black_level;

  cbdata = (GUPnPAsyncData *) userdata;
  red_video_black_level = ((renderingcontrol_red_video_black_level_query_callback)cbdata->cb) (service,
                                                                                               cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, red_video_black_level);
}

gulong
renderingcontrol_red_video_black_level_query_connect (GUPnPService *service,
                                                      renderingcontrol_red_video_black_level_query_callback callback,
                                                      gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::RedVideoBlackLevel",
                                G_CALLBACK (_renderingcontrol_red_video_black_level_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable GreenVideoBlackLevel */

typedef guint (*renderingcontrol_green_video_black_level_query_callback) (GUPnPService *service,
                                                                          gpointer userdata);

static void
_renderingcontrol_green_video_black_level_query_cb (GUPnPService *service,
                                                    gchar *variable,
                                                    GValue *value,
                                                    gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint green_video_black_level;

  cbdata = (GUPnPAsyncData *) userdata;
  green_video_black_level = ((renderingcontrol_green_video_black_level_query_callback)cbdata->cb) (service,
                                                                                                   cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, green_video_black_level);
}

gulong
renderingcontrol_green_video_black_level_query_connect (GUPnPService *service,
                                                        renderingcontrol_green_video_black_level_query_callback callback,
                                                        gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::GreenVideoBlackLevel",
                                G_CALLBACK (_renderingcontrol_green_video_black_level_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable BlueVideoBlackLevel */

typedef guint (*renderingcontrol_blue_video_black_level_query_callback) (GUPnPService *service,
                                                                         gpointer userdata);

static void
_renderingcontrol_blue_video_black_level_query_cb (GUPnPService *service,
                                                   gchar *variable,
                                                   GValue *value,
                                                   gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint blue_video_black_level;

  cbdata = (GUPnPAsyncData *) userdata;
  blue_video_black_level = ((renderingcontrol_blue_video_black_level_query_callback)cbdata->cb) (service,
                                                                                                 cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, blue_video_black_level);
}

gulong
renderingcontrol_blue_video_black_level_query_connect (GUPnPService *service,
                                                       renderingcontrol_blue_video_black_level_query_callback callback,
                                                       gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::BlueVideoBlackLevel",
                                G_CALLBACK (_renderingcontrol_blue_video_black_level_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable ColorTemperature */

typedef guint (*renderingcontrol_color_temperature_query_callback) (GUPnPService *service,
                                                                    gpointer userdata);

static void
_renderingcontrol_color_temperature_query_cb (GUPnPService *service,
                                              gchar *variable,
                                              GValue *value,
                                              gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint color_temperature;

  cbdata = (GUPnPAsyncData *) userdata;
  color_temperature = ((renderingcontrol_color_temperature_query_callback)cbdata->cb) (service,
                                                                                       cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, color_temperature);
}

gulong
renderingcontrol_color_temperature_query_connect (GUPnPService *service,
                                                  renderingcontrol_color_temperature_query_callback callback,
                                                  gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::ColorTemperature",
                                G_CALLBACK (_renderingcontrol_color_temperature_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable HorizontalKeystone */

typedef gint (*renderingcontrol_horizontal_keystone_query_callback) (GUPnPService *service,
                                                                     gpointer userdata);

static void
_renderingcontrol_horizontal_keystone_query_cb (GUPnPService *service,
                                                gchar *variable,
                                                GValue *value,
                                                gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gint horizontal_keystone;

  cbdata = (GUPnPAsyncData *) userdata;
  horizontal_keystone = ((renderingcontrol_horizontal_keystone_query_callback)cbdata->cb) (service,
                                                                                           cbdata->userdata);
  g_value_init (value, G_TYPE_INT);
  g_value_set_int (value, horizontal_keystone);
}

gulong
renderingcontrol_horizontal_keystone_query_connect (GUPnPService *service,
                                                    renderingcontrol_horizontal_keystone_query_callback callback,
                                                    gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::HorizontalKeystone",
                                G_CALLBACK (_renderingcontrol_horizontal_keystone_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable VerticalKeystone */

typedef gint (*renderingcontrol_vertical_keystone_query_callback) (GUPnPService *service,
                                                                   gpointer userdata);

static void
_renderingcontrol_vertical_keystone_query_cb (GUPnPService *service,
                                              gchar *variable,
                                              GValue *value,
                                              gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gint vertical_keystone;

  cbdata = (GUPnPAsyncData *) userdata;
  vertical_keystone = ((renderingcontrol_vertical_keystone_query_callback)cbdata->cb) (service,
                                                                                       cbdata->userdata);
  g_value_init (value, G_TYPE_INT);
  g_value_set_int (value, vertical_keystone);
}

gulong
renderingcontrol_vertical_keystone_query_connect (GUPnPService *service,
                                                  renderingcontrol_vertical_keystone_query_callback callback,
                                                  gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::VerticalKeystone",
                                G_CALLBACK (_renderingcontrol_vertical_keystone_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable Mute */

typedef gboolean (*renderingcontrol_mute_query_callback) (GUPnPService *service,
                                                          gpointer userdata);

static void
_renderingcontrol_mute_query_cb (GUPnPService *service,
                                 gchar *variable,
                                 GValue *value,
                                 gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gboolean mute;

  cbdata = (GUPnPAsyncData *) userdata;
  mute = ((renderingcontrol_mute_query_callback)cbdata->cb) (service,
                                                             cbdata->userdata);
  g_value_init (value, G_TYPE_BOOLEAN);
  g_value_set_boolean (value, mute);
}

gulong
renderingcontrol_mute_query_connect (GUPnPService *service,
                                     renderingcontrol_mute_query_callback callback,
                                     gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::Mute",
                                G_CALLBACK (_renderingcontrol_mute_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable Volume */

typedef guint (*renderingcontrol_volume_query_callback) (GUPnPService *service,
                                                         gpointer userdata);

static void
_renderingcontrol_volume_query_cb (GUPnPService *service,
                                   gchar *variable,
                                   GValue *value,
                                   gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  guint volume;

  cbdata = (GUPnPAsyncData *) userdata;
  volume = ((renderingcontrol_volume_query_callback)cbdata->cb) (service,
                                                                 cbdata->userdata);
  g_value_init (value, G_TYPE_UINT);
  g_value_set_uint (value, volume);
}

gulong
renderingcontrol_volume_query_connect (GUPnPService *service,
                                       renderingcontrol_volume_query_callback callback,
                                       gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::Volume",
                                G_CALLBACK (_renderingcontrol_volume_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable VolumeDB */

typedef gint (*renderingcontrol_volume_db_query_callback) (GUPnPService *service,
                                                           gpointer userdata);

static void
_renderingcontrol_volume_db_query_cb (GUPnPService *service,
                                      gchar *variable,
                                      GValue *value,
                                      gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gint volume_db;

  cbdata = (GUPnPAsyncData *) userdata;
  volume_db = ((renderingcontrol_volume_db_query_callback)cbdata->cb) (service,
                                                                       cbdata->userdata);
  g_value_init (value, G_TYPE_INT);
  g_value_set_int (value, volume_db);
}

gulong
renderingcontrol_volume_db_query_connect (GUPnPService *service,
                                          renderingcontrol_volume_db_query_callback callback,
                                          gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::VolumeDB",
                                G_CALLBACK (_renderingcontrol_volume_db_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


/* state variable Loudness */

typedef gboolean (*renderingcontrol_loudness_query_callback) (GUPnPService *service,
                                                              gpointer userdata);

static void
_renderingcontrol_loudness_query_cb (GUPnPService *service,
                                     gchar *variable,
                                     GValue *value,
                                     gpointer userdata)
{
  GUPnPAsyncData *cbdata;
  gboolean loudness;

  cbdata = (GUPnPAsyncData *) userdata;
  loudness = ((renderingcontrol_loudness_query_callback)cbdata->cb) (service,
                                                                     cbdata->userdata);
  g_value_init (value, G_TYPE_BOOLEAN);
  g_value_set_boolean (value, loudness);
}

gulong
renderingcontrol_loudness_query_connect (GUPnPService *service,
                                         renderingcontrol_loudness_query_callback callback,
                                         gpointer userdata)
{
  GUPnPAsyncData *cbdata;

  cbdata = (GUPnPAsyncData *) g_slice_alloc (sizeof (*cbdata));
  cbdata->cb = G_CALLBACK (callback);
  cbdata->userdata = userdata;

  return g_signal_connect_data (service,
                                "query-variable::Loudness",
                                G_CALLBACK (_renderingcontrol_loudness_query_cb),
                                cbdata,
                                _free_cb_data,
                                (GConnectFlags) 0);
}


G_END_DECLS

#endif /* GUPNP_GENERATED_CLIENT_BINDING_RENDERINGCONTROL */
