.TH AUTOIP 8 "February 2004" "Howl 0.9.3"
.SH NAME 
autoip - internet address self-assigner
.SH SYNOPSIS
\fBautoip\fR [\fIoptions\fR]
.SH DESCRIPTION
The \fBautoipd\fR daemon configures an IPv4 Link-Local address for a
single network interface according to the IETF Zeronconf draft standard.
When run, \fBautoipd\fR automatically puts itself in the background, then finds and claims an
available IPv4 Link-Local address. \fBautoipd\fR determines an appropriate Link-Local
address, configures the address, then continues running to monitor for
collisions on that address. When necessary, \fBautoipd\fR finds a new address.
.SH OPTIONS
.TP
.B \-h
Display brief help message
.TP
.B \-v
Display version information
.TP
.B \-d
Run in debug mode
.TP
.B \-i  
Use interface \fIifname\fR
.TP
.B \-s
Start at IP address \fIaddr\fR
.TP
.B \-m
Use this mac address
.SH "SEE ALSO"
.BR nifd (8),
.BR mDNSResponder (8)
